Resources:
  MyEc2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: "solution"
      ImageId: "ami-053b0d53c279acc90"
      InstanceType: "t2.small"
      SubnetId: "subnet-0987492a31edb1a7b"
  MyVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: '8'
      AvailabilityZone: us-east-1d
  Attachment:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref MyEc2Instance
      VolumeId: !Ref MyVolume
      Device: /dev/sdh



        