Resources:
  MyEc2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: "mumbai"
      ImageId: "ami-0f5ee92e2d63afc18"
      InstanceType: "t2.small"

  MyVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: '50'
      AvailabilityZone: ap-south-1a
  Attachment:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref MyEc2Instance
      VolumeId: !Ref MyVolume
      Device: /dev/sdh



        