Resources:
  NewKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: "so"

  MyEc2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref NewKeyPair
      ImageId: "ami-053b0d53c279acc90"
      InstanceType: "t2.micro"
      SubnetId: "subnet-1195677a"

  MyVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: '8'
      AvailabilityZone: us-east-1a

  Attachment:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref MyEc2Instance
      VolumeId: !Ref MyVolume
      Device: /dev/sdh
